config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tasks

get "password", to: "passwords#edit", as: :edit_password
patch "password", to: "passwords#update"

get "sign_up", to: "registrations#new"
post "sign_up", to: "registrations#create"

get "sign_in",  to: "sessions#new"
post "sign_in", to: "sessions#create"

delete "logout", to: "sessions#destroy"

get "password/reset", to: "password_resets#new"
post "password/reset", to: "password_resets#create"
get "password/reset/edit", to: "password_resets#edit"
patch "password/reset/edit", to: "password_resets#update"

root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tag.rb
class Tag < ApplicationRecord
   belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
has_many :tags
  has_many :task_assignments
  has_many :assigned_users, through: :task_assignments, source: :user

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :due_date, presence: true

  enum status:{
    incomplete: 0,
    complete: 1
  }

  enum priority: {
    low: 0,
    medium: 1,
    high: 2
  }
end

app/models/task_assignment.rb
class TaskAssignment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format:  { with: /\A[^@\s]+@[^@\s]+\z/, message:"must be a valid email address"}
  validates :username, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
def index

end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  def set_current_user
    puts "Current User: #{current_user.inspect}"
  end
  def set_current_user
    if session[:user_id]
    Current.user = User.find_by(id:session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
  end
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/helpers/profile_helper.rb
module ProfileHelper
end

app/controllers/helpers/profiles_helper.rb
module ProfilesHelper
end

app/controllers/helpers/tasks_helper.rb
module TasksHelper
end

app/controllers/helpers/user_helper.rb
module UserHelper
end

app/controllers/main_controller.rb
class MainController < ApplicationController
def index
   end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email:params[:email])
    if @user.present?
      #send email
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path, notice: "If an account with that email was found, we have sent a link too reset your password."
  end

  def edit
   @user = User.find_signed!(params[:token],purpose: "password_reset")
   rescue ActiveSupport::MessageVerifier::InvalidSignature
   redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "You password was reset successfully. Please sign in."
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
 end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
 before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
   redirect_to root_path, notice: "Password updated!"
   else
     render :edit
   end
  end


  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
   @user = User.new(user_params)
    if @user.save
     session[:user_id] = @user.id
     redirect_to root_path, notice: "Successfully created account"
    else
     render :new
    end
  end

 private

  def user_params
   params.require(:user).permit(:username, :email, :date_of_birth, :phone_number, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end




  def create
    @user = User.find_by(email: params[:email])
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
   session[:user_id] = nil
   redirect_to root_path, notice: "Logged out"

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
   @tasks = Task.all


    if ['high', 'medium', 'low'].include?(params[:priority])
      @tasks = @tasks.where(priority: params[:priority])
    end

    if params[:status].present?
      @tasks = @tasks.where(status: params[:status])
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
   @task = Task.find(params[:id])
    if @task.update(task_params)
      assign_users_to_task
     redirect_to tasks_path, notice: 'Task updated successfully'
    else
      render 'edit'
    end
  end

  def new
   @task = Task.new
  end

  def create
    if params[:task][:status] == 'incomplete'
     @task = Task.new(task_params)
     if @task.save
       assign_users_to_task
      redirect_to tasks_path, notice: 'Task created successfully'
     else
       logger.debug @task.errors.full_messages
       render 'new'
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, alert: "Removed Succesfully "
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :due_date, :status, :priority)
  end

 def assign_users_to_task
  if params[:task][:assigned_user_ids].present?
    @task.assigned_user_ids = params[:task][:assigned_user_ids]
   else
     @task.assigned_user_ids = []
   end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
  end

  def create
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/about/index.html.erb
<h1>About Us <h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
 crossorigin="anonymous">
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
 integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
  crossorigin="anonymous"></script>

   <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   <%= javascript_importmap_tags %>
 </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container">
  <%= render partial: "shared/flash"%>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center" style="background-color: grey;">

</div>

 <h1>Welcome to Todo Application</h1>
 <p>A TodoApp is a simple yet essential tool for task management.
  It allows users to create, organize, and track their tasks or to-do items efficiently.
   Users can add tasks, set due dates, categorize them, and mark them as complete when finished.
    TodoApps are commonly used for personal productivity, project management, and team collaboration,
     providing a convenient way to stay organized and ensure that tasks are completed on time."
 </p>
</div>


app/views/password_resets/edit.html.erb
<h1>Reset your password </h1>

   <%= form_with model: @user, url:password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
       <div class="alert alert-danger">
          <% @user.errors.full_messages.each do |message| %>
             <div><%= message %></div>
          <% end %>
       </div>
   <% end %>

   <div class="mb-3">
     <%= form.label :password%>
     <%= form.password_field :password, class: "form-control", placeholder:"password" %>
   </div>

   <div class="mb-3">
     <%= form.label :password_confirmation  %>
     <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
   </div>

   <div class="mb-3">
      <%= form.submit "Reset Password", class: "btn btn-primary" %>
   </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password </h1>
<%= form_with url:password_reset_path do |form| %>

  <% if form.object.errors.any? %>
     <div class="alert alert-danger">
      <% form.errors.full_messages.each do |message| %>
     <div><%= message %></div>
     <% end %>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder: "imran123@.com" %>
   </div>

  <div class="mb-3">
   <%=form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
 <div class="alert alert-info mt-4" role="alert" >
   <%=flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
 <div class="alert alert-warning mt-4" role="alert">
   <%= flash[:alert]%>
 </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
   <%= link_to "TodoApp", root_path, class: "navbar-brand" %>
   <button class="navbar-toggler" type="button"
    data-bs-toggle="collapse" data-bs-target="#navbarNav"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
     <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
       <%=link_to "My Task", tasks_path, class: "nav-link"%>
      </li>
    </ul>

    <ul class="navbar-nav ms-auto mb-2 m-lg-0">
       <% if Current.user %>
         <li class="nav-item">
           <%= link_to Current.user.email, edit_password_path, class: "nav-link"  %>
         </li>
         <li class="nav-item">
           <%= link_to "My Profile", user_path(Current.user), class: "nav-link" %>
         </li>
         <li class="nav-item">
           <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
         </li>
       <% else %>
         <li class="nav-item">
           <%= link_to "Sign Up",sign_up_path, class: "nav-link" %>
         </li>
         <li class="nav-item">
           <%= link_to "Login", sign_in_path, class: "nav-link" %>
         </li>
       <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tasks/edit.html.erb
<h3>Update a Task</h3>

<%= form_with model: @task, class: "form" do |f| %>
  <% if @task.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter your title" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter your description" %>
  </div>

  <div class="form-group">
    <%= f.label :due_date %>
    <%= f.text_field :due_date, class: "form-control", placeholder: "Due Date" %>
  </div>

  <div class="form-group">
    <%= f.label :status, class: "d-block" %>
    <%= f.select :status, Task.statuses.keys, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :priority %>
    <%= f.select :priority, [['High', 'high'], ['Medium', 'medium'], ['Low', 'low']], {}, class: "form-control" %>
  </div>

<div class="form-group">
  <%= f.label :assigned_user_ids, "Assign Users", class: "d-block" %>
  <%= f.select :assigned_user_ids, User.all.collect { |u| [u.name, u.id] }, {}, multiple: true, class: "form-control" %>
</div>

  <%= f.submit "Update Task", class: "btn btn-primary" %>
<% end %>

app/views/tasks/index.html.erb
<%= link_to 'Add new Task', new_task_path, class: 'btn btn-primary' %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>

        <td><%= link_to task.title, task_path(task) %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Edit', edit_task_path(task), class: 'btn btn-warning', method: 'get' %></td>
        <td>
          <%= button_to 'Remove', task_path(task), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure' } %>
        </td>
      </tr>
      <td>
       <% task.assigned_users.each do |user| %>
       <%= user.name %><br>
       <% end %>
       </td>
    <% end %>
  </tbody>
</table>

<%= form_with url: tasks_path, method: :get, class: 'form-inline' do |form| %>
  <div class="form-group">
    <%= form.label :priority, class: 'mr-2' %>
    <%= form.select :priority, [['High', 'high'], ['Medium', 'medium'], ['Low', 'low']], class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :status, "Filter by Status:", class: 'ml-2 mr-2' %>
    <%= form.select :status, options_for_select([["All", ""], ["Incomplete", "incomplete"], ["Complete", "complete"]], params[:status]), class: 'form-control' %>
  </div>
  <%= form.submit "Search", class: 'btn btn-primary' %>
<% end %>

app/views/tasks/new.html.erb
<h3>Create a Task</h3>

<%= form_with model: @task, class: "form" do |f| %>
  <% if @task.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter your title" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter your description" %>
  </div>

  <div class="form-group">
    <%= f.label :due_date %>
    <%= f.date_field :due_date, class: "form-control", placeholder: "Due Date" %>
  </div>

  <div class="form-group">
    <%= f.label :status, class: "d-block" %>
    <%= f.select :status, Task.statuses.keys, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :priority %>
    <%= f.select :priority, [['High', 'high'], ['Medium', 'medium'], ['Low', 'low']], {}, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :assigned_user_ids, "Assign Users", class: "d-block" %>
  <%= f.select :assigned_user_ids, User.all.collect { |u| [u.name, u.id] }, {}, multiple: true, class: "form-control" %>
</div>


  <%= f.submit "Create Task", class: "btn btn-primary" %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task Detail</h1>

<%= form_with model: @task, class: "form" do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", readonly: true %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", readonly: true %>
  </div>

  <div class="form-group">
    <%= f.label :due_date %>
    <%= f.text_field :due_date, class: "form-control", readonly: true %>
  </div>

  <div class="form-group">
    <%= f.label :status, class: "d-block" %>
    <%= f.text_field :status, class: "form-control", readonly: true %>
  </div>
<% end %>

app/views/users/index.html.erb
<table border>
  <% @users.each do |user| %>
    <tr>

     <td><%= user.email %></td>

    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/users/show.html.erb
<h1>Profile page </h1>

<%= form_with model: @user do |f| %>
<%= f.label :username %><br>
  <%= f.text_field :username, readonly: true %><br>

<%= f.label :email %><br>
  <%= f.text_field :email, readonly: true %><br>

  <%= f.label :date_of_birth %><br>
  <%= f.text_field :date_of_birth, readonly: true %><br>

<%= f.label :phone_number %><br>
  <%= f.text_field :phone_number, readonly: true %><br>
<% end %>